export const extensionCopy = {
  extensionTitle: "Ground Control",
  extensionSubtitle: "Documentation status for this page",
  extensionLoading: "Checking this page",
  extensionUnavailable: "Ground Control could not reach the server.",
  extensionUnsupported: "Open a GitHub README, Confluence page, or docs page.",
  extensionUnknown: "This page is not watched yet.",
  extensionKnown: "This page is watched.",
  extensionNoClaims: "No claim results are recorded for this page yet.",
  extensionClaimsCount: "Claims on page",
  extensionPage: "Page",
  extensionRepo: "Repository",
  extensionStatus: "Status",
  extensionDegrees: "Degrees of drift",
  extensionViewRepo: "Open repository telemetry",
  extensionCheck: "Check this README",
  extensionChecking: "Starting README check",
  extensionCheckDone: "Check requested. Results will appear after processing.",
  extensionCheckFailed: "The README check could not start.",
  extensionWatch: "Watch this page for",
  extensionWatching: "Adding watched page",
  extensionWatchDone: "Page added. Claim marks appear after its first scan.",
  extensionWatchReload: "Page added. Reload this tab to show claim marks.",
  extensionMarksReload: "Reload this tab to update claim marks.",
  extensionWatchFailed: "The page could not be added.",
  extensionPermissionDenied: "Allow this site to show claim marks.",
  extensionNoRepos: "Connect a repository to watch this page.",
  extensionSignIn: "Sign in with GitHub",
  extensionSigningIn: "Opening GitHub sign-in",
  extensionSignInFailed: "Sign-in did not complete.",
  extensionSignOut: "Sign out",
  extensionSignOutFailed: "The server could not end this session.",
  extensionSignedInAs: "Signed in as",
  extensionClaimVerified: "Verified",
  extensionClaimDrifting: "Drifting",
  extensionClaimUnconfirmed: "Unconfirmed",
  extensionClaimDisputed: "Disputed",
  extensionOpenFix: "Open fix",
  extensionEvidenceUnavailable: "No further evidence is available yet.",
  extensionClaimQuote: "Documented claim",
} as const;
