export const webCopy = {
  brand: "Ground Control",
  navSky: "The Sky",
  navConnect: "Connect a repo",
  navMyRepos: "My repos",
  navSources: "Add a source",
  navSignIn: "Sign in",
  navSignedInAs: "Signed in as",
  navSignOut: "Sign out",
  navReports: "My reports",
  navAccount: "Account menu",
  navAvatarAlt: "GitHub profile picture",
  navSignedOut: "Not signed in",
  reportsTitle: "My reports",
  reportsIntro:
    "Every repository you have connected, with the documents it watches and each check run.",
  reportsSignIn:
    "Sign in with GitHub to see the repositories you have connected.",
  reportsEmpty:
    "No repositories connected yet. Connect one to start checking its documentation.",
  reportsConnect: "Connect a repository",
  reportsDocuments: "Watched documents",
  reportsAddDocument: "Add a document",
  reportsOpenRepo: "Open repository",
  reportsBack: "Back to my reports",
  navMenu: "Menu",
  navHome: "Back to the Sky",
  navSkip: "Skip to content",
  appTagline: "Documentation checks with evidence",
  pageNotFound: "That view is not available.",
  stageMode: "Stage view",
  skyTitle: "The Sky",
  skySubtitle:
    "Explore repository checks and find documentation that needs review.",
  skyModeLive: "Live scan",
  skyModeCached: "Cached scan",
  skyModeSimulated: "Simulated layout",
  skyModeEmpty: "No scans yet",
  skyModeUnavailable: "No scan available",
  skyUpdated: "Updated",
  skyDataStale: "Live connection unavailable. Showing a saved scan.",
  skyDataFailed: "The Sky could not load. Check the server and try again.",
  skyLoading: "Loading the Sky",
  skyEmptyTitle: "No repositories scanned yet",
  skyEmptyBody:
    "Run a public scan or enter a repository below to start filling the Sky.",
  skyRefresh: "Refresh scan",
  skyLegendTitle: "How to read the Sky",
  skyLegendSummary: "How this map works",
  skyLegendTopic: "Angle groups repositories by topic.",
  skyLegendLag:
    "Farther from center means more days since the README changed relative to code. Distance uses a compressed scale.",
  skyLegendStars: "Larger marks mean more GitHub stars, on a log scale.",
  skyLegendDrift:
    "An amber outline means a possible mismatch to review; a broken amber ring means confirmed drift.",
  skyLegendSimulated: "Dashed hollow marks are simulated.",
  skyLegendHolding:
    "Outlined ovals in the outer orbit are your unscanned repos. Their position has no measured meaning.",
  skyCanvasAlt:
    "Representative star chart of repositories by topic, README lag, stars, and check status, with unscanned account repositories in an outer holding orbit. The list below contains every repository for keyboard access.",
  skyTopicFrameworks: "Frameworks",
  skyTopicUi: "UI libraries",
  skyTopicBuild: "Build tools",
  skyTopicBackend: "Back end",
  skyTopicOther: "Other",
  skyShowing: "Showing",
  skyOf: "of",
  skyMapShown: "repositories on the map",
  skyMapBrowse: "Browse every repository in the list below",
  skyFindingsTitle: "Measured findings",
  skyRealCount: "Real repos scanned",
  skyDriftingCount: "Repos with drift",
  skyReviewCount: "Need review",
  skyMedianLag: "Median README lag",
  skyNoFindings: "No measured findings yet. Simulated points are excluded.",
  skyBrowseTitle: "Repositories",
  skyPreviewAction: "Preview",
  skyBrowseSearch: "Find a repository",
  skyBrowsePlaceholder: "owner/repo",
  skyScopeLabel: "Repository scope",
  skyScopeMine: "My repos",
  skyScopePublic: "All public repos",
  skyScopeMineHint:
    "Your GitHub repositories, including private ones. Enable deep checks for a repository you own after connecting it.",
  skyScopePublicHint:
    "Public repositories outside your account. Their scans read documentation and metadata only; they never run repository code.",
  skyMyReposSignIn: "Sign in with GitHub to see your repositories here.",
  scanTiersTitle: "What each scan tier checks",
  scanTiersSummary: "Scan levels: Static, AI, Deep",
  scanTiersIntro:
    "The tier shown on a result tells you which evidence was actually collected.",
  scanTierStatic: "1 · Static",
  scanTierStaticBody:
    "Reads the README, repository files, and metadata. It does not install or run repository code.",
  scanTierAi: "2 · AI",
  scanTierAiBody:
    "Extracts cited documentation claims for static checks. It still does not execute repository code.",
  scanTierDeep: "3 · Deep",
  scanTierDeepBody:
    "Runs the reviewed flight checks in your own repository's GitHub Action or an owner-approved local checkout. Public repos need an explicit personal-repo opt-in.",
  skyUnscannedTag: "Unscanned",
  skyHoldingTitle: "Unscanned repository",
  skyHoldingPublic:
    "This public repository has not been checked. Its holding-orbit position is not a status measurement.",
  skyHoldingPrivate:
    "This private repository has not sent check results. Connect it from My repos to opt in to CI checks.",
  skyHoldingChecked:
    "This repository has check results. Its holding-orbit position does not encode README lag or stars.",
  skyHoldingConnect: "Open My repos",
  skyListPrevious: "Previous repositories",
  skyListNext: "Next repositories",
  skyListPage: "Page",
  skyNoMatches: "No repositories match that search.",
  skyListCount: "Repositories shown",
  skyInspectorTitle: "Selected repository",
  skyInspectorIntro: "Snapshot of the selected repository",
  skySelectPrompt:
    "Select a point or choose a repository from the list to see its scan.",
  skySimulatedNotice: "Simulated for layout; not a real scan.",
  skyPossibleDriftNotice:
    "A documentation claim may be outdated. Review the finding before treating it as drift.",
  skyPreviewReview: "possible mismatch to review",
  skyPreviewReviews: "possible mismatches to review",
  skyPreviewConfirmed: "confirmed failing check",
  skyPreviewConfirmedMany: "confirmed failing checks",
  skyPreviewPassed: "checks passed",
  skyPreviewNoChecks: "Open the repository result to see its checks.",
  skyPreviewQuote: "README says",
  skyPreviewNoCiFailure: "Unconfirmed findings do not fail CI.",
  skyScanDetails: "Scan details",
  skyTierStatic: "Static",
  skyTierAi: "AI",
  skyTierDeep: "Deep",
  skyDeepStatus: "Latest deep CI result",
  skyNoEvidence: "No detailed check evidence is available for this snapshot.",
  skyEvidenceLoading: "Loading check evidence",
  skyEvidenceTitle: "Failing facts",
  skyEvidenceNoFailures: "No confirmed failing facts in the latest run.",
  skySource: "Source",
  skyReadme: "Open README at scanned commit",
  skyOpenRepo: "Review findings",
  skyOpenRepoResult: "See repository result",
  skyRepo: "Repository",
  skyCommit: "Scanned commit",
  skyTiers: "Tiers run",
  skyStars: "GitHub stars",
  skyLag: "README lag",
  skyDegrees: "Degrees of drift",
  skyTopic: "Topic",
  skyDaysUnit: "days",
  skyDegreesUnit: "degrees",
  skyScanTitle: "Check a public README",
  skyScanLabel: "GitHub repository",
  skyScanPlaceholder: "owner/repo",
  skyScanAction: "Check this README",
  skyScanPending: "Starting scan",
  skyScanQueued:
    "Scan requested. Results will appear when processing finishes.",
  skyScanCached: "Saved results are ready in the Sky.",
  skyScanLimit: "This hour's free checks are used. Try again later or sign in.",
  skyScanError:
    "The scan could not start. Check the repository name and try again.",
  skyScanPrivacy:
    "Public checks inspect docs and metadata only. They never install dependencies or run repository code.",
  skyBulkScanButton: "Scan unscanned public READMEs",
  skyBulkScanHint: "Documentation only; repository code will not run.",
  statusOnCourse: "On course",
  statusDrifting: "Drifting",
  statusCorrected: "Corrected",
  statusLostSignal: "Lost signal",
  statusNoTelemetry: "No telemetry",
  statusPossibleDrift: "Possible drift",
  statusUnknown: "Status unavailable",
  statusSymbolOnCourse: "●",
  statusSymbolDrifting: "◖",
  statusSymbolCorrected: "◎",
  statusSymbolLostSignal: "◇",
  statusSymbolNoTelemetry: "○",
  statusSymbolPossibleDrift: "◌",
  repoLoading: "Loading repository telemetry",
  repoBackToSky: "Back to the Sky",
  repoResultTitle: "What this scan found",
  repoReviewOne: "1 possible mismatch",
  repoReviewMany: "possible mismatches",
  repoConfirmedOne: "1 confirmed mismatch",
  repoConfirmedMany: "confirmed mismatches",
  repoNoMismatch: "No confirmed mismatches found",
  repoNoVerdict: "No detailed check results yet",
  repoReviewExplanation:
    "This claim has not been confirmed. It does not fail CI or notify an author until reviewed.",
  repoConfirmedExplanation:
    "A previously confirmed documentation check failed at this commit.",
  repoNoMismatchExplanation:
    "The saved checks found no confirmed drift at this commit.",
  repoPassedChecks: "Checks passed",
  repoNeedsReview: "Need review",
  repoUnverifiedChecks: "Could not verify",
  repoFindingNeedsReview: "Needs review",
  repoFindingConfirmed: "Confirmed drift",
  repoFindingMissingPath:
    "The README references this path, but the scanner could not find it at the scanned commit.",
  repoFindingOther:
    "This documentation claim did not match the evidence collected at the scanned commit.",
  repoFindingOpenSource: "See the README line",
  repoFindingOpenRun: "View all check evidence",
  repoFindingsMore: "More findings are in the full check evidence.",
  repoFindingLoading: "Loading saved check results…",
  repoTechnicalDetails: "History and technical details",
  repoSourceDetails: "Source sync details",
  repoSourceOpen: "View source",
  repoTrajectoryShort:
    "A trend appears after at least two saved runs. This repository has one so far.",
  repoNotScanned: "Not scanned yet",
  repoScanTitle: "Public README check",
  repoRescanAction: "Refresh README check",
  repoScanIntro:
    "This repository is connected, but a public README scan has not run yet.",
  repoScanReady: "Last public scan",
  repoScanTiers: "Tiers completed",
  repoDeepReady:
    "Deep checks enabled. Add the Ground Control Action to send CI results.",
  repoDeepAvailable:
    "Own this public repo? Enable deep checks from My repos after signing in.",
  repoScanLimited:
    "The README was scanned, but there are not enough confirmed checks for a status verdict.",
  repoScanQueued: "Scan requested. This page updates when the check finishes.",
  repoScanFailed: "The README check could not start. Try again.",
  repoPrivatePending:
    "This private repository has no CI check results yet. Add the Ground Control Action to report a run.",
  repoUnavailable: "This repository could not be opened.",
  repoAccessDenied:
    "Sign in with a GitHub account that can read this repository.",
  repoPrivate: "Private repository",
  repoPublic: "Public repository",
  repoSources: "Watched sources",
  repoNoSources:
    "No sources are watched yet. Add a source to check its claims.",
  repoRuns: "Recent runs",
  repoRunTier: "Tier",
  repoRunPublic: "Static / AI",
  repoRunDeep: "Deep CI",
  repoRunUnknown: "Earlier run",
  repoNoRuns: "No runs yet. Push a commit or request a check.",
  repoTrajectory: "Documentation trajectory",
  repoTrajectoryEmpty:
    "A trajectory needs run results. Recent telemetry is listed below.",
  repoTrajectoryLoading: "Loading measured trajectory",
  repoTrajectoryUnavailable:
    "Run details are unavailable. Recent telemetry is listed below.",
  repoTrajectoryNote:
    "Dashed is the documented path. Solid is measured code drift at each commit.",
  repoDial: "Degrees of drift",
  repoCommit: "Commit",
  repoCheckedAt: "Checked at",
  repoViewRun: "View run",
  repoAddSource: "Add a source",
  repoRunStatus: "Confirmed check verdict",
  repoRunNoConfirmedFailures: "No confirmed failures",
  repoRunFailures: "Failing checks",
  runTitle: "Run detail",
  runNoConfirmedFailures: "No confirmed failures",
  runLoading: "Loading run detail",
  runUnavailable: "This run could not be opened.",
  runAccessDenied: "Sign in with a GitHub account that can read this run.",
  runEvidence: "Grouped failing facts",
  runNoEvidence: "No confirmed failing facts in this run.",
  runOpenSource: "Open source at claim",
  runChecks: "Checks",
  runNoChecks: "This run has no recorded checks.",
  runExpected: "Expected",
  runActual: "Actual",
  runQuote: "Documented claim",
  runTrust: "Trust state",
  runStateUnconfirmed: "Unconfirmed",
  runStateConfirmed: "Confirmed",
  runStateDisputed: "Disputed",
  runStateDropped: "Dropped",
  runPass: "Passed",
  runFail: "Failed",
  runSkipped: "Skipped",
  runUnverified: "Unverified",
  runConfirm: "Confirm check",
  runDrop: "Drop check",
  runConfirmDone:
    "Check confirmed. Its current result now counts toward drift.",
  runDropDone:
    "Check dropped. The quote stays suppressed until its text changes.",
  runActionFailed:
    "The check could not be updated. Check your access and try again.",
  sourceTitle: "Watch another document",
  sourceIntro:
    "Connect a page to a repository so future code changes can check its claims.",
  sourceRepoLabel: "Connected repository",
  sourceKindLabel: "Source kind",
  sourceUrlLabel: "Page URL",
  sourceAction: "Add source",
  sourcePending: "Adding source",
  sourceDone:
    "Source added. Fetch status appears below; claim results follow a scan.",
  sourceFailed:
    "The source could not be added. Check the URL and repository access.",
  sourceDisclosure:
    "When Gemini is configured, source text is sent to it for claim extraction.",
  sourceSignIn: "Sign in to add a source to a connected repository.",
  sourceKindConfluence: "Confluence page",
  sourceKindUrl: "Public docs URL",
  sourceViewRepo: "Open connected repository",
  sourceClaims: "claims",
  sourceSyncTitle: "Source status",
  sourceSyncFresh: "Fresh",
  sourceSyncPending: "Pending",
  sourceSyncError: "Fetch failed",
  sourceSyncUnknown: "No fetch status is available yet.",
  sourceSyncFetched: "Last fetched",
  sourceSyncVersion: "Page version",
  sourceSyncHash: "Content hash",
  sourceSyncProblem: "Fetch problem",
  sourceSyncCheck: "Check status",
  sourceSyncChecking: "Checking source status",
  sourceSyncRefresh: "Refresh source",
  sourceSyncRefreshing: "Refreshing source",
  sourceSyncRefreshDone: "Source refresh finished.",
  sourceSyncFetchFailed:
    "The source was checked, but its page could not be fetched.",
  sourceSyncCheckFailed: "Source status could not be loaded.",
  sourceSyncRefreshFailed: "Source refresh could not start.",
  sourceSyncAdminRequired:
    "Repository admin access is needed to refresh this source.",
  connectTitle: "Connect a repository",
  connectIntro:
    "Any public repo can receive static and optional AI checks. Repositories you own can also run deep checks after an explicit Actions setup.",
  connectRuntimeOption: "Enable deep checks for a public repository I own",
  connectRuntimeHint:
    "Deep checks run repository code only in the repo's GitHub Action or an owner-approved local checkout.",
  connectRepoLabel: "GitHub repository",
  connectAction: "Connect repository",
  connectPending: "Connecting repository",
  connectDonePrivate:
    "Private repository connected. Save its CI token now; it will not be shown again.",
  connectDonePublic:
    "Public repository connected for documentation checks. Enable deep checks separately if you own it.",
  connectDonePublicRuntime:
    "Deep checks enabled for your public repository. Save its Actions token now; it will not be shown again.",
  connectDonePublicRuntimeExisting:
    "Deep checks are already enabled for your public repository. Keep using its existing Actions token; reconnecting does not show it again.",
  connectTokenTitle: "Set up GitHub Actions",
  connectTokenOnce:
    "This telemetry token is shown only once. Store it as an Actions secret before leaving this page.",
  connectTokenLabel: "One-time telemetry token",
  connectTokenCopy: "Copy token",
  connectTokenCopied: "Token copied. Add it as the repository Actions secret.",
  connectTokenCopyManual:
    "Clipboard access is unavailable. The token is selected for manual copying.",
  connectTokenShow: "Show token",
  connectTokenHide: "Hide token",
  connectTokenSecret: "Repository Actions secret:",
  connectServerVariable: "Repository Actions variable:",
  connectHostedActionHint:
    "GitHub-hosted Actions need an HTTPS tunnel to this server. Open Ground Control through that HTTPS origin before copying the URL.",
  connectFailed:
    "The repository could not be connected. Check administrator access and try again.",
  connectVisibilityChanged:
    "This repository was previously private. Its stored private results must be cleared before connecting it as public.",
  connectSignIn: "Sign in with GitHub to connect a repository.",
  imessageTitle: "Link iMessage",
  imessageIntro:
    "Receive drift alerts and request corrections by replying to iMessage.",
  imessagePhoneLabel: "Your iMessage phone number",
  imessagePhonePlaceholder: "+15551234567",
  imessagePhoneHint: "Include the country code, with no spaces or punctuation.",
  imessageInvalidPhone: "Enter a phone number like +15551234567.",
  imessageAction: "Send linking message",
  imessagePending: "Sending linking message",
  imessageSent:
    "Check Messages on your phone and reply with the LINK code shown in the message. The code works once and expires in 24 hours.",
  imessageRateLimit:
    "Three linking messages have been requested this hour. Try again later.",
  imessageUnavailable: "iMessage linking is not configured on this server.",
  imessageFailed: "The linking message could not be sent.",
  signInTitle: "Sign in with GitHub",
  accountTitle: "Your Ground Control account",
  signInIntro:
    "Sign in to connect repositories, add sources, and review checks you can access.",
  signInAction: "Continue with GitHub",
  signInConnected: "Signed in as",
  signInUnavailable:
    "Account status is unavailable. Try again after the server responds.",
  accountReposTitle: "Your GitHub repositories",
  accountReposIntro:
    "Your accessible repositories appear here after sign-in. Listing them does not start a scan or run their code.",
  accountReposLoading: "Loading your GitHub repositories",
  accountReposFailed:
    "Your repositories could not be loaded from GitHub. Try refreshing this page.",
  accountReposEmpty: "No accessible repositories were returned by GitHub.",
  accountReposSearch: "Find one of your repositories",
  accountReposSearchPlaceholder: "Search by name or description",
  accountReposFilter: "Show repositories",
  accountReposFilterAll: "All repositories",
  accountReposFilterUnscanned: "Unscanned repositories",
  accountReposPagePrevious: "Previous page",
  accountReposPageNext: "Next page",
  accountReposPageOf: "of",
  accountReposNoMatches: "No repositories match that search.",
  accountReposTruncated:
    "Showing the first 500 recently updated repositories. Bulk scan applies to these repositories.",
  accountReposPublic: "Public",
  accountReposPrivate: "Private",
  accountReposArchived: "Archived",
  accountReposFork: "Fork",
  accountReposConnected: "Connected",
  accountReposRuntimeEnabled: "Deep checks enabled",
  accountReposChecked: "Checked",
  accountReposScanned: "Scanned",
  accountReposOpenResult: "Open result",
  accountReposNotAdmin: "Admin access is needed to connect this repository.",
  accountReposConnect: "Connect",
  accountReposEnableRuntime: "Enable deep checks",
  accountReposConnecting: "Connecting",
  accountReposScan: "Check README",
  accountReposScanning: "Requesting scan",
  accountReposScanAll: "Scan all public READMEs",
  accountReposScanAllProgress: "Public scans requested",
  accountReposScanAllDone: "Public scan requests finished",
  accountReposScanAllFailed: "Some public scans could not start",
  accountReposScanQueued: "Scan queued",
  accountReposScanCached: "Saved scan ready",
  accountReposScanFailed: "This README scan could not start.",
  accountReposConnectFailed: "This repository could not be connected.",
  accountReposPrivateHint:
    "Private repositories need an explicit connection and GitHub Action for runtime checks.",
  accountReposPublicHint:
    "Ordinary public scans inspect documentation and metadata only. Your own public repositories can opt into deep checks in their GitHub Action.",
  accountReposManual: "Add a repository by name",
  formRepoHint: "Use owner/repo from GitHub.",
  formUrlHint: "Paste an https page address.",
  formUrlPlaceholder: "https://docs.example.com/page",
  formInvalidRepo: "Enter a GitHub repository as owner/repo.",
  formInvalidUrl: "Enter a valid https URL.",
  commonRetry: "Try again",
  commonBack: "Back",
  commonUnknown: "Unknown",
  commonNone: "None recorded",
  commonOpen: "Open",
  commonSuccess: "Success",
  commonFailure: "Failure",
  commonPending: "Pending",
  commonLoading: "Loading",
  sourceNoRepos:
    "No repositories are connected yet. Connect one before adding a source.",
} as const;
