export const webCopy = {
  brand: "Ground Control",
  navSky: "The Sky",
  navConnect: "Connect a repo",
  navMyRepos: "My repos",
  navSources: "Add a source",
  navSignIn: "Sign in",
  navSignedInAs: "Signed in as",
  navSignOut: "Sign out",
  navMenu: "Menu",
  navHome: "Back to the Sky",
  navSkip: "Skip to content",
  appTagline: "Documentation checks with evidence",
  pageNotFound: "That view is not available.",
  stageMode: "Stage view",
  skyTitle: "Documentation, in orbit",
  skySubtitle: "Each point is a public repository at one scanned commit.",
  skyModeLive: "Live scan",
  skyModeCached: "Cached scan",
  skyModeSimulated: "Simulated layout",
  skyModeUnavailable: "No scan available",
  skyUpdated: "Updated",
  skyDataStale: "Live connection unavailable. Showing a saved scan.",
  skyDataFailed: "The Sky could not load. Check the server and try again.",
  skyLoading: "Loading the Sky",
  skyEmptyTitle: "No repositories scanned yet",
  skyEmptyBody:
    "Run a public scan or enter a repository below to start filling the Sky.",
  skyRefresh: "Refresh scan",
  skyLegendTitle: "How to read the Sky",
  skyLegendTopic: "Angle groups repositories by topic.",
  skyLegendLag:
    "Farther from center means more days since the README changed relative to code.",
  skyLegendStars: "Larger marks mean more GitHub stars, on a log scale.",
  skyLegendDrift: "Amber and a broken ring mean drifting checks.",
  skyLegendSimulated: "Dashed hollow marks are simulated.",
  skyCanvasAlt:
    "Star chart of public repositories by topic, README lag, stars, and check status. Use the repository list below for keyboard access.",
  skyTopicFrameworks: "Frameworks",
  skyTopicUi: "UI libraries",
  skyTopicBuild: "Build tools",
  skyTopicBackend: "Back end",
  skyTopicOther: "Other",
  skyShowing: "Showing",
  skyOf: "of",
  skyFindingsTitle: "Measured findings",
  skyRealCount: "Real repos scanned",
  skyDriftingCount: "Repos with drift",
  skyMedianLag: "Median README lag",
  skyNoFindings: "No measured findings yet. Simulated points are excluded.",
  skyBrowseTitle: "Browse satellites",
  skyBrowseSearch: "Find a repository",
  skyBrowsePlaceholder: "owner/repo",
  skyNoMatches: "No repositories match that search.",
  skyListCount: "Repositories shown",
  skyInspectorTitle: "Selected repository",
  skySelectPrompt:
    "Select a point or choose a repository from the list to see its scan.",
  skySimulatedNotice: "Simulated for layout; not a real scan.",
  skyPossibleDriftNotice:
    "First-scan findings are unconfirmed. They do not fail CI or notify an author.",
  skyNoEvidence: "No detailed check evidence is available for this snapshot.",
  skyEvidenceLoading: "Loading check evidence",
  skyEvidenceTitle: "Failing facts",
  skyEvidenceNoFailures: "No confirmed failing facts in the latest run.",
  skySource: "Source",
  skyReadme: "Open README at scanned commit",
  skyOpenRepo: "Open repository view",
  skyRepo: "Repository",
  skyCommit: "Scanned commit",
  skyTiers: "Tiers run",
  skyStars: "GitHub stars",
  skyLag: "README lag",
  skyDegrees: "Degrees of drift",
  skyTopic: "Topic",
  skyDaysUnit: "days",
  skyDegreesUnit: "degrees",
  skyScanTitle: "Check a public README",
  skyScanLabel: "GitHub repository",
  skyScanPlaceholder: "owner/repo",
  skyScanAction: "Check this README",
  skyScanPending: "Starting scan",
  skyScanQueued:
    "Scan requested. Results will appear when processing finishes.",
  skyScanCached: "Saved results are ready in the Sky.",
  skyScanLimit: "This hour's free checks are used. Try again later or sign in.",
  skyScanError:
    "The scan could not start. Check the repository name and try again.",
  skyScanPrivacy:
    "Public checks inspect docs and metadata only. They never install dependencies or run repository code.",
  statusOnCourse: "On course",
  statusDrifting: "Drifting",
  statusCorrected: "Corrected",
  statusLostSignal: "Lost signal",
  statusNoTelemetry: "No telemetry",
  statusPossibleDrift: "Possible drift",
  statusUnknown: "Status unavailable",
  statusSymbolOnCourse: "●",
  statusSymbolDrifting: "◖",
  statusSymbolCorrected: "◎",
  statusSymbolLostSignal: "◇",
  statusSymbolNoTelemetry: "○",
  statusSymbolPossibleDrift: "◌",
  repoLoading: "Loading repository telemetry",
  repoUnavailable: "This repository could not be opened.",
  repoAccessDenied:
    "Sign in with a GitHub account that can read this repository.",
  repoPrivate: "Private repository",
  repoPublic: "Public repository",
  repoSources: "Watched sources",
  repoNoSources:
    "No sources are watched yet. Add a source to check its claims.",
  repoRuns: "Recent runs",
  repoNoRuns: "No runs yet. Push a commit or request a check.",
  repoTrajectory: "Documentation trajectory",
  repoTrajectoryEmpty:
    "A trajectory needs run results. Recent telemetry is listed below.",
  repoTrajectoryLoading: "Loading measured trajectory",
  repoTrajectoryUnavailable:
    "Run details are unavailable. Recent telemetry is listed below.",
  repoTrajectoryNote:
    "Dashed is the documented path. Solid is measured code drift at each commit.",
  repoDial: "Degrees of drift",
  repoCommit: "Commit",
  repoCheckedAt: "Checked at",
  repoViewRun: "View run",
  repoAddSource: "Add a source",
  repoRunStatus: "Verdict",
  repoRunFailures: "Failing checks",
  runTitle: "Run detail",
  runLoading: "Loading run detail",
  runUnavailable: "This run could not be opened.",
  runAccessDenied: "Sign in with a GitHub account that can read this run.",
  runEvidence: "Grouped failing facts",
  runNoEvidence: "No confirmed failing facts in this run.",
  runOpenSource: "Open source at claim",
  runChecks: "Checks",
  runNoChecks: "This run has no recorded checks.",
  runExpected: "Expected",
  runActual: "Actual",
  runQuote: "Documented claim",
  runTrust: "Trust state",
  runStateUnconfirmed: "Unconfirmed",
  runStateConfirmed: "Confirmed",
  runStateDisputed: "Disputed",
  runStateDropped: "Dropped",
  runPass: "Passed",
  runFail: "Failed",
  runSkipped: "Skipped",
  runUnverified: "Unverified",
  runConfirm: "Confirm check",
  runDrop: "Drop check",
  runConfirmDone:
    "Check confirmed. Its current result now counts toward drift.",
  runDropDone:
    "Check dropped. The quote stays suppressed until its text changes.",
  runActionFailed:
    "The check could not be updated. Check your access and try again.",
  sourceTitle: "Watch another document",
  sourceIntro:
    "Connect a page to a repository so future code changes can check its claims.",
  sourceRepoLabel: "Connected repository",
  sourceKindLabel: "Source kind",
  sourceUrlLabel: "Page URL",
  sourceAction: "Add source",
  sourcePending: "Adding source",
  sourceDone:
    "Source added. Fetch status appears below; claim results follow a scan.",
  sourceFailed:
    "The source could not be added. Check the URL and repository access.",
  sourceDisclosure:
    "When Gemini is configured, source text is sent to it for claim extraction.",
  sourceSignIn: "Sign in to add a source to a connected repository.",
  sourceKindConfluence: "Confluence page",
  sourceKindUrl: "Public docs URL",
  sourceViewRepo: "Open connected repository",
  sourceClaims: "claims",
  sourceSyncTitle: "Source status",
  sourceSyncFresh: "Fresh",
  sourceSyncPending: "Pending",
  sourceSyncError: "Fetch failed",
  sourceSyncUnknown: "No fetch status is available yet.",
  sourceSyncFetched: "Last fetched",
  sourceSyncVersion: "Page version",
  sourceSyncHash: "Content hash",
  sourceSyncProblem: "Fetch problem",
  sourceSyncCheck: "Check status",
  sourceSyncChecking: "Checking source status",
  sourceSyncRefresh: "Refresh source",
  sourceSyncRefreshing: "Refreshing source",
  sourceSyncRefreshDone: "Source refresh finished.",
  sourceSyncFetchFailed:
    "The source was checked, but its page could not be fetched.",
  sourceSyncCheckFailed: "Source status could not be loaded.",
  sourceSyncRefreshFailed: "Source refresh could not start.",
  sourceSyncAdminRequired:
    "Repository admin access is needed to refresh this source.",
  connectTitle: "Connect a repository",
  connectIntro:
    "Connected private repositories can run code checks in their own CI. Connected public repositories receive static and optional AI checks only.",
  connectRepoLabel: "GitHub repository",
  connectAction: "Connect repository",
  connectPending: "Connecting repository",
  connectDonePrivate:
    "Private repository connected. Save its CI token now; it will not be shown again.",
  connectDonePublic:
    "Public repository connected for documentation checks. It gets no code checks, Actions token, or generated flightcheck commits.",
  connectTokenTitle: "Set up GitHub Actions",
  connectTokenOnce:
    "This telemetry token is shown only once. Store it as an Actions secret before leaving this page.",
  connectTokenLabel: "One-time telemetry token",
  connectTokenCopy: "Copy token",
  connectTokenCopied: "Token copied. Add it as the repository Actions secret.",
  connectTokenCopyManual:
    "Clipboard access is unavailable. The token is selected for manual copying.",
  connectTokenShow: "Show token",
  connectTokenHide: "Hide token",
  connectTokenSecret: "Repository Actions secret:",
  connectServerVariable: "Repository Actions variable:",
  connectHostedActionHint:
    "GitHub-hosted Actions need an HTTPS tunnel to this server. Open Ground Control through that HTTPS origin before copying the URL.",
  connectFailed:
    "The repository could not be connected. Check administrator access and try again.",
  connectVisibilityChanged:
    "This repository was previously private. Its stored private results must be cleared before connecting it as public.",
  connectSignIn: "Sign in with GitHub to connect a repository.",
  imessageTitle: "Link iMessage",
  imessageIntro:
    "Receive drift alerts and request corrections by replying to iMessage.",
  imessagePhoneLabel: "Your iMessage phone number",
  imessagePhonePlaceholder: "+15551234567",
  imessagePhoneHint: "Include the country code, with no spaces or punctuation.",
  imessageInvalidPhone: "Enter a phone number like +15551234567.",
  imessageAction: "Send linking message",
  imessagePending: "Sending linking message",
  imessageSent:
    "Check Messages on your phone and reply with the LINK code shown in the message. The code works once and expires in 24 hours.",
  imessageRateLimit:
    "Three linking messages have been requested this hour. Try again later.",
  imessageUnavailable: "iMessage linking is not configured on this server.",
  imessageFailed: "The linking message could not be sent.",
  signInTitle: "Sign in with GitHub",
  accountTitle: "Your Ground Control account",
  signInIntro:
    "Sign in to connect repositories, add sources, and review checks you can access.",
  signInAction: "Continue with GitHub",
  signInConnected: "Signed in as",
  signInUnavailable:
    "Account status is unavailable. Try again after the server responds.",
  accountReposTitle: "Your GitHub repositories",
  accountReposIntro:
    "Your accessible repositories appear here after sign-in. Listing them does not start a scan or run their code.",
  accountReposLoading: "Loading your GitHub repositories",
  accountReposFailed:
    "Your repositories could not be loaded from GitHub. Try refreshing this page.",
  accountReposEmpty: "No accessible repositories were returned by GitHub.",
  accountReposSearch: "Find one of your repositories",
  accountReposSearchPlaceholder: "Search by name or description",
  accountReposNoMatches: "No repositories match that search.",
  accountReposTruncated:
    "Showing the first 500 recently updated repositories. Bulk scan applies to these repositories.",
  accountReposPublic: "Public",
  accountReposPrivate: "Private",
  accountReposArchived: "Archived",
  accountReposFork: "Fork",
  accountReposConnected: "Connected",
  accountReposScanned: "Scanned",
  accountReposOpenResult: "Open result",
  accountReposNotAdmin: "Admin access is needed to connect this repository.",
  accountReposConnect: "Connect",
  accountReposConnecting: "Connecting",
  accountReposScan: "Check README",
  accountReposScanning: "Requesting scan",
  accountReposScanAll: "Scan all public READMEs",
  accountReposScanAllProgress: "Public scans requested",
  accountReposScanAllDone: "Public scan requests finished",
  accountReposScanAllFailed: "Some public scans could not start",
  accountReposScanQueued: "Scan queued",
  accountReposScanCached: "Saved scan ready",
  accountReposScanFailed: "This README scan could not start.",
  accountReposConnectFailed: "This repository could not be connected.",
  accountReposPrivateHint:
    "Private repositories need an explicit connection and GitHub Action for runtime checks.",
  accountReposPublicHint:
    "Public scans inspect documentation and metadata only. They never run repository code.",
  accountReposManual: "Add a repository by name",
  formRepoHint: "Use owner/repo from GitHub.",
  formUrlHint: "Paste an https page address.",
  formUrlPlaceholder: "https://docs.example.com/page",
  formInvalidRepo: "Enter a GitHub repository as owner/repo.",
  formInvalidUrl: "Enter a valid https URL.",
  commonRetry: "Try again",
  commonBack: "Back",
  commonUnknown: "Unknown",
  commonNone: "None recorded",
  commonOpen: "Open",
  commonSuccess: "Success",
  commonFailure: "Failure",
  commonPending: "Pending",
  commonLoading: "Loading",
  sourceNoRepos:
    "No repositories are connected yet. Connect one before adding a source.",
} as const;
