export const webCopy = {
  brand: "Ground Control",
  navSky: "The Sky",
  navConnect: "Connect a repo",
  navMyRepos: "My repos",
  navSources: "Add a source",
  navSignIn: "Sign in",
  navSignedInAs: "Signed in as",
  navSignOut: "Sign out",
  navReports: "My reports",
  navAccount: "Account menu",
  navAvatarAlt: "GitHub profile picture",
  navSignedOut: "Not signed in",
  reportsTitle: "My reports",
  reportsIntro:
    "Every repository you have connected, with the documents it watches and each check run.",
  reportsSignIn:
    "Sign in with GitHub to see the repositories you have connected.",
  reportsEmpty:
    "No repositories connected yet. Connect one to start checking its documentation.",
  reportsConnect: "Connect a repository",
  reportsDocuments: "Watched documents",
  reportsAddDocument: "Add a document",
  reportsOpenRepo: "Open repository",
  reportsBack: "Back to my reports",
  deepScanAddAction: "Add deep scan",
  deepChecksSetupAction: "Set up deep checks",
  deepScanTitle: "Add deep scan",
  deepScanIntro:
    "Choose a repository you own, then enable deep checks and add the Ground Control Action in its GitHub Actions settings.",
  navMenu: "Menu",
  navHome: "Back to the Sky",
  navSkip: "Skip to content",
  appTagline: "Documentation checks with evidence",
  pageNotFound: "That view is not available.",
  stageMode: "Stage view",
  skyTitle: "The Sky",
  skySubtitle:
    "Explore repository checks and find documentation that needs review.",
  skyModeLive: "Live scan",
  skyModeCached: "Cached scan",
  skyModeSimulated: "Simulated layout",
  skyModeEmpty: "No scans yet",
  skyModeUnavailable: "No scan available",
  skyUpdated: "Updated",
  skyDataStale: "Live connection unavailable. Showing a saved scan.",
  skyDataFailed: "The Sky could not load. Check the server and try again.",
  skyLoading: "Loading the Sky",
  skyEmptyTitle: "No repositories scanned yet",
  skyEmptyBody:
    "Run a public scan or enter a repository below to start filling the Sky.",
  skyRefresh: "Refresh scan",
  skyLegendTitle: "How to read the Sky",
  skyLegendSummary: "How this map works",
  skyLegendTopic: "Angle groups repositories by topic.",
  skyLegendLag:
    "Farther from center means more days since the README changed relative to code. Distance uses a compressed scale.",
  skyLegendStars:
    "Larger dots mean more GitHub stars. Crowded dots shrink to make room for every repo.",
  skyLegendDrift:
    "An amber outline means a possible mismatch to review; a broken amber ring means confirmed drift.",
  skyLegendSimulated: "Dashed hollow marks are simulated.",
  skyLegendHolding:
    "Outlined ovals in the outer orbit are your unscanned repos. Their position has no measured meaning.",
  skyLegendNoChecks:
    "Hollow circles are scanned READMEs with no checkable results yet. The scan did not fail.",
  skyCanvasAlt:
    "Star chart showing every filtered repository by topic, README lag, stars, and check status, with unscanned account repositories in an outer holding orbit. The list below provides keyboard access.",
  skyZoomIn: "Zoom in",
  skyZoomOut: "Zoom out",
  skyZoomHint: "Drag to pan when zoomed in.",
  skyTopicFrameworks: "Frameworks",
  skyTopicUi: "UI libraries",
  skyTopicBuild: "Build tools",
  skyTopicBackend: "Back end",
  skyTopicOther: "Other",
  skyShowing: "Showing",
  skyOf: "of",
  skyMapShown: "repositories on the map",
  skyMapBrowse: "Browse every repository in the list below",
  skyMapGuide:
    "Bigger dot: more stars · Hollow circle: no checkable result · Outer oval: unscanned repo",
  skyFindingsTitle: "Measured findings",
  skyRealCount: "Real repos scanned",
  skyDriftingCount: "Repos with drift",
  skyReviewCount: "Need review",
  skyMedianLag: "Median README lag",
  skyNoFindings: "No measured findings yet. Simulated points are excluded.",
  skyBrowseTitle: "Repositories",
  skyPreviewAction: "Preview",
  skyScopeLabel: "Repository scope",
  skyScopeMine: "My repos",
  skyScopePublic: "All public repos",
  skyScopeMineHint:
    "Your GitHub repositories, including private ones. Enable deep checks for a repository you own after connecting it.",
  skyScopePublicHint:
    "Public repositories outside your account. Their scans read documentation and metadata only; they never run repository code.",
  skyMyReposSignIn: "Sign in with GitHub to see your repositories here.",
  scanTiersTitle: "What each scan tier checks",
  scanTiersSummary: "Scan levels: Static, AI, Deep",
  scanTiersIntro:
    "The tier shown on a result tells you which evidence was actually collected.",
  scanTierStatic: "1 · Static",
  scanTierStaticBody:
    "Reads the README, repository files, and metadata. It does not install or run repository code.",
  scanTierAi: "2 · AI",
  scanTierAiBody:
    "Extracts cited documentation claims for static checks. It still does not execute repository code.",
  scanTierDeep: "3 · Deep",
  scanTierDeepBody:
    "Runs the reviewed flight checks in your own repository's GitHub Action or an owner-approved local checkout. Public repos need an explicit personal-repo opt-in.",
  skyUnscannedTag: "Unscanned",
  skyHoldingTitle: "Unscanned repository",
  skyHoldingPublic:
    "This public repository has not been checked. Its holding-orbit position is not a status measurement.",
  skyHoldingPrivate:
    "This private repository has not sent check results. Connect it from My repos to opt in to CI checks.",
  skyHoldingChecked:
    "This repository has check results. Its holding-orbit position does not encode README lag or stars.",
  skyHoldingConnect: "Open My repos",
  skyListPrevious: "Previous repositories",
  skyListNext: "Next repositories",
  skyListPage: "Page",
  skyNoMatches: "No repositories match that search.",
  skyListCount: "Repositories shown",
  skyInspectorTitle: "Selected repository",
  skyInspectorIntro: "Snapshot of the selected repository",
  skySelectPrompt:
    "Select a point or choose a repository from the list to see its scan.",
  skySimulatedNotice: "Simulated for layout; not a real scan.",
  skyPossibleDriftNotice:
    "A documentation claim may be outdated. Review the finding before treating it as drift.",
  skyPreviewReview: "possible mismatch to review",
  skyPreviewReviews: "possible mismatches to review",
  skyPreviewConfirmed: "confirmed failing check",
  skyPreviewConfirmedMany: "confirmed failing checks",
  skyPreviewPassed: "checks passed",
  skyPreviewNoChecks: "Open the repository result to see its checks.",
  skyPreviewQuote: "README says",
  skyPreviewNoCiFailure: "Unconfirmed findings do not fail CI.",
  skyScanDetails: "Scan details",
  skyTierStatic: "Static",
  skyTierAi: "AI",
  skyTierDeep: "Deep",
  skyDeepStatus: "Latest deep CI result",
  skyNoEvidence: "No detailed check evidence is available for this snapshot.",
  skyEvidenceLoading: "Loading check evidence",
  skyEvidenceTitle: "Failing facts",
  skyEvidenceNoFailures: "No confirmed failing facts in the latest run.",
  skySource: "Source",
  skyReadme: "Open README at scanned commit",
  skyOpenRepo: "Review findings",
  skyOpenRepoResult: "See repository result",
  skyRepo: "Repository",
  skyCommit: "Scanned commit",
  skyTiers: "Tiers run",
  skyStars: "GitHub stars",
  skyLag: "README lag",
  skyDegrees: "Degrees of drift",
  skyTopic: "Topic",
  skyDaysUnit: "days",
  skyDegreesUnit: "degrees",
  skyScanTitle: "Check a public README",
  skyScanLabel: "GitHub repository",
  skyScanPlaceholder: "owner/repo or a GitHub link",
  skyScanAction: "Check this README",
  skyScanPending: "Starting scan",
  skyScanQueued:
    "Scan requested. Results will appear when processing finishes.",
  skyScanCached: "Saved results are ready.",
  skyScanSeeResult: "See the result for",
  skyScanLimit: "This hour's free checks are used. Try again later or sign in.",
  skyScanError:
    "The scan could not start. Check the repository name and try again.",
  skyScanPrivacy:
    "Public checks inspect docs and metadata only. They never install dependencies or run repository code.",
  skyBulkScanButton: "Scan unscanned public READMEs",
  skyBulkScanHint: "Documentation only; repository code will not run.",
  statusOnCourse: "On course",
  statusDrifting: "Drifting",
  statusCorrected: "Corrected",
  statusLostSignal: "Lost signal",
  statusNoTelemetry: "No verified checks",
  statusPossibleDrift: "Possible drift",
  statusUnknown: "Status unavailable",
  statusSymbolOnCourse: "●",
  statusSymbolDrifting: "◖",
  statusSymbolCorrected: "◎",
  statusSymbolLostSignal: "◇",
  statusSymbolNoTelemetry: "○",
  statusSymbolPossibleDrift: "◌",
  repoLoading: "Loading repository telemetry",
  repoBackToSky: "Back to the Sky",
  repoOpenGithub: "Open on GitHub",
  repoHeadWrongOne: "1 README instruction is out of date",
  repoHeadWrongMany: "README instructions are out of date",
  repoHeadMaybeOne: "1 README instruction might be out of date",
  repoHeadMaybeMany: "README instructions might be out of date",
  repoHeadOk: "The README matches the code",
  repoHeadUnchecked: "We couldn't test this README automatically",
  repoHeadNothing: "Nothing to test in this README",
  repoHeadNotChecked: "This README hasn't been checked yet",
  repoHeadNoResults: "No results yet",
  repoSubWrong: "The code changed, but these README lines didn't.",
  repoSubMaybe:
    "These look wrong, but nobody has confirmed them yet, so they won't send alerts.",
  repoSubOkOne: "We tested 1 instruction and it's correct.",
  repoSubOkMany: "instructions tested, all correct.",
  repoSubUnchecked:
    "We found instructions, but testing them would mean running the code.",
  repoSubNothing:
    "We look for things we can test, like commands, file paths and ports, and didn't find any.",
  repoSubNotChecked:
    "Checking only reads the README and repo files. It never runs the code.",
  repoSubPrivate:
    "Results show up here after the Ground Control Action runs in this repo's CI.",
  repoCheckedOn: "Checked",
  repoScanLimited:
    "The README was scanned, but no claim could be checked with the available tiers. This is not a scan failure.",
  repoCheckAgain: "Check again",
  repoCheckNow: "Check this README",
  repoChecking: "Checking…",
  repoChecklistTitle: "What we tested",
  repoClaimWrong: "Out of date",
  repoClaimMaybe: "Might be out of date",
  repoClaimUnchecked: "Couldn't test",
  repoClaimOk: "Correct",
  repoMarkWrong: "✕",
  repoMarkMaybe: "△",
  repoMarkUnchecked: "?",
  repoMarkOk: "✓",
  repoReasonMissingPath: "This file or folder isn't in the repo anymore.",
  repoReasonOther: "This no longer matches the code.",
  repoSeeInReadme: "See in README",
  repoSeeAllResults: "See all results",
  repoOwnerTitle: "Is this your repo?",
  repoOwnerBody: "Get a text when its README goes out of date.",
  repoOwnerAction: "Set up alerts",
  repoDetailsTitle: "Details",
  repoDetailsCommit: "Checked commit",
  repoDetailsMethods: "Checked with",
  repoMethodStatic: "file scan",
  repoMethodAi: "AI reading",
  repoMethodDeep: "your CI",
  repoOtherDocs: "Other docs we check",
  repoNoMismatchExplanation:
    "The saved checks found no confirmed drift at this commit.",
  repoFindingLoading: "Loading saved check results…",
  findingFix: "Fix with a pull request",
  findingFixAll: "Fix all in one pull request",
  findingFixPending: "Drafting a correction…",
  findingFixWorking:
    "An AI model is drafting a README edit from your repository's files. This can take a minute.",
  findingFixOpened: "Review the draft pull request",
  findingFixNone:
    "The model couldn't find a safe correction from the repository files. Edit the README line directly or ignore this finding.",
  findingFixAccess:
    "Sign in again with an account that can push to this repository.",
  findingFixFailed:
    "The draft pull request could not be opened. Check the repository's write access and try again.",
  findingFixSkipped:
    "findings had no safe correction and were left out of the pull request.",
  findingIgnore: "Ignore",
  findingIgnorePending: "Ignoring…",
  findingIgnoreFailed:
    "The finding could not be ignored. Check your access and try again.",
  repoSourceDetails: "Source sync details",
  repoSourceOpen: "View source",
  repoTrajectoryShort:
    "A trend appears after at least two saved runs. This repository has one so far.",
  repoScanQueued: "Scan requested. This page updates when the check finishes.",
  repoScanFailed: "The README check could not start. Try again.",
  repoUnavailable: "This repository could not be opened.",
  repoAccessDenied:
    "Sign in with a GitHub account that can read this repository.",
  repoPrivate: "Private repository",
  repoPublic: "Public repository",
  repoNoSources:
    "No sources are watched yet. Add a source to check its claims.",
  repoRuns: "Recent runs",
  repoRunTier: "Tier",
  repoRunPublic: "Static / AI",
  repoRunDeep: "Deep CI",
  repoRunUnknown: "Earlier run",
  repoNoRuns: "No runs yet. Push a commit or request a check.",
  repoTrajectory: "Documentation trajectory",
  repoTrajectoryEmpty:
    "A trajectory needs run results. Recent telemetry is listed below.",
  repoTrajectoryLoading: "Loading measured trajectory",
  repoTrajectoryUnavailable:
    "Run details are unavailable. Recent telemetry is listed below.",
  repoTrajectoryNote:
    "Dashed is the documented path. Solid is measured code drift at each commit.",
  repoDial: "Degrees of drift",
  repoCommit: "Commit",
  repoCheckedAt: "Checked at",
  repoViewRun: "View run",
  repoAddSource: "Add a source",
  repoRunStatus: "Confirmed check verdict",
  repoRunNoConfirmedFailures: "No confirmed failures",
  repoRunFailures: "Failing checks",
  runTitle: "Run detail",
  runNoConfirmedFailures: "No confirmed failures",
  runLoading: "Loading run detail",
  runUnavailable: "This run could not be opened.",
  runAccessDenied: "Sign in with a GitHub account that can read this run.",
  runEvidence: "Grouped failing facts",
  runNoEvidence: "No confirmed failing facts in this run.",
  runOpenSource: "Open source at claim",
  runChecks: "Checks",
  runNoChecks: "This run has no recorded checks.",
  runExpected: "Expected",
  runActual: "Actual",
  runQuote: "Documented claim",
  runTrust: "Trust state",
  runStateUnconfirmed: "Unconfirmed",
  runStateConfirmed: "Confirmed",
  runStateDisputed: "Disputed",
  runStateDropped: "Dropped",
  runPass: "Passed",
  runFail: "Failed",
  runSkipped: "Skipped",
  runUnverified: "Unverified",
  runConfirm: "Confirm check",
  runDrop: "Drop check",
  runConfirmDone:
    "Check confirmed. Its current result now counts toward drift.",
  runDropDone:
    "Check dropped. The quote stays suppressed until its text changes.",
  runActionFailed:
    "The check could not be updated. Check your access and try again.",
  sourceTitle: "Watch another document",
  sourceIntro:
    "Connect a page to a repository so future code changes can check its claims.",
  sourceRepoLabel: "Connected repository",
  sourceKindLabel: "Source kind",
  sourceUrlLabel: "Page URL",
  sourceAction: "Add source",
  sourcePending: "Adding source",
  sourceDone:
    "Source added. Fetch status appears below; claim results follow a scan.",
  sourceFailed:
    "The source could not be added. Check the URL and repository access.",
  sourceDisclosure:
    "When Gemini is configured, source text is sent to it for claim extraction.",
  sourceSignIn: "Sign in to add a source to a connected repository.",
  sourceKindConfluence: "Confluence page",
  sourceKindUrl: "Public docs URL",
  sourceViewRepo: "Open connected repository",
  sourceClaims: "claims",
  sourceSyncTitle: "Source status",
  sourceSyncFresh: "Fresh",
  sourceSyncPending: "Pending",
  sourceSyncError: "Fetch failed",
  sourceSyncUnknown: "No fetch status is available yet.",
  sourceSyncFetched: "Last fetched",
  sourceSyncVersion: "Page version",
  sourceSyncHash: "Content hash",
  sourceSyncProblem: "Fetch problem",
  sourceSyncCheck: "Check status",
  sourceSyncChecking: "Checking source status",
  sourceSyncRefresh: "Refresh source",
  sourceSyncRefreshing: "Refreshing source",
  sourceSyncRefreshDone: "Source refresh finished.",
  sourceSyncFetchFailed:
    "The source was checked, but its page could not be fetched.",
  sourceSyncCheckFailed: "Source status could not be loaded.",
  sourceSyncRefreshFailed: "Source refresh could not start.",
  sourceSyncAdminRequired:
    "Repository admin access is needed to refresh this source.",
  connectTitle: "Connect a repository",
  connectIntro:
    "Connect a repository you administer, or check a public GitHub README and add its result to the Sky. Public checks never run repository code.",
  connectBackToRepos: "Back to my repos",
  connectChooseSource: "Where is the repository?",
  connectMineOption: "One of my repositories",
  connectMineSearch: "Find one of your repositories",
  connectMineSelect: "Choose a repository",
  connectMinePlaceholder: "Select a repository",
  connectMineEmpty: "No repositories you can administer were found.",
  connectPublicOption: "Check a public GitHub repository",
  connectPublicLabel: "Public GitHub repository",
  connectPublicPlaceholder: "https://github.com/owner/repo",
  connectPublicHint:
    "Paste the repository URL or enter owner/repo. Its README result joins the Sky; this check does not connect the repo to your account.",
  connectPublicOpenSky: "See this repository in the Sky",
  connectRuntimeOption: "Enable deep checks for a public repository I own",
  connectRuntimeHint:
    "Deep checks run repository code only in the repo's GitHub Action or an owner-approved local checkout.",
  connectRepoLabel: "GitHub repository",
  connectAction: "Connect repository",
  connectPending: "Connecting repository",
  connectDonePrivate:
    "Private repository connected. Save its CI token now; it will not be shown again.",
  connectDonePublic:
    "Public repository connected for documentation checks. Enable deep checks separately if you own it.",
  connectDonePublicRuntime:
    "Deep checks enabled for your public repository. Save its Actions token now; it will not be shown again.",
  connectDonePublicRuntimeExisting:
    "Deep checks are already enabled for your public repository. Keep using its existing Actions token; reconnecting does not show it again.",
  connectTokenTitle: "Save your Actions token",
  connectTokenOnce:
    "This token appears only once. Save it as a repository Actions secret before leaving this page.",
  connectTokenExisting:
    "Keep the existing Actions secret. If it is lost, open deep-check setup to issue a new token.",
  connectRotateTitle: "Lost the Actions token?",
  connectRotateHint:
    "Issue a new one-time token only if needed. This replaces the current token, so update the repository's GROUND_CONTROL_TOKEN secret before its next CI report.",
  connectRotateAction: "Issue new token",
  connectTokenLabel: "One-time telemetry token",
  connectTokenCopy: "Copy token",
  connectTokenCopied: "Token copied. Add it as the repository Actions secret.",
  connectTokenCopyManual:
    "Clipboard access is unavailable. The token is selected for manual copying.",
  connectTokenShow: "Show token",
  connectTokenHide: "Hide token",
  connectSecretPrompt:
    "Copy the token, run this command anywhere with GitHub CLI, then paste the token at its prompt. It never appears in the command or shell history.",
  connectSecretCommand: "gh secret set GROUND_CONTROL_TOKEN -R {repo}",
  connectSecretGitHub: "Use GitHub settings instead",
  connectStepsTitle: "Set up deep checks",
  connectStepsIntro:
    "Ground Control publishes the generated flight checks to your repository. Add one small GitHub workflow to run them on pull requests and default-branch pushes.",
  connectChecksTitle: "Add the workflow",
  connectStepPlan:
    "Download this short workflow. It calls Ground Control's maintained workflow, which runs the checks and sends the report.",
  connectDefaultBranchLabel: "Default branch for push checks",
  connectHostedUrl: "Ground Control server URL is already filled in:",
  connectHostedUrlMissing:
    "Open this page on your hosted HTTPS Ground Control server to download a workflow with its URL filled in.",
  connectStepWorkflow: "Add the downloaded file to your repository at",
  connectWorkflowDownload: "Download workflow",
  connectVerifyTitle: "Open a test pull request",
  connectStepRun:
    "Run this PowerShell command after the workflow and Actions secret are ready. It clones this repository into a temporary folder, creates an empty commit, pushes a test branch, and opens a pull request. The Ground Control check and report appear in Actions; the first passing run establishes a baseline.",
  connectSmokeCommand: `$repo = '{repo}'
$branch = 'ground-control-smoke-' + (Get-Date -Format 'yyyyMMddHHmmssfff')
$checkout = Join-Path ([IO.Path]::GetTempPath()) $branch
gh repo clone $repo $checkout
if ($LASTEXITCODE -ne 0) { throw 'Clone failed' }
$base = git -C $checkout branch --show-current
if ($LASTEXITCODE -ne 0 -or -not $base) { throw 'Default branch lookup failed' }
git -C $checkout switch -c $branch
if ($LASTEXITCODE -ne 0) { throw 'Branch creation failed' }
git -C $checkout commit --allow-empty -m 'Test Ground Control checks'
if ($LASTEXITCODE -ne 0) { throw 'Empty commit failed' }
git -C $checkout push --set-upstream origin $branch
if ($LASTEXITCODE -ne 0) { throw 'Push failed' }
gh pr create -R $repo --base $base --head $branch --title 'Test Ground Control checks' --body 'Smoke test with an empty commit and no file changes.'
if ($LASTEXITCODE -ne 0) { throw 'Pull request creation failed' }`,
  connectCommandCopy: "Copy command",
  connectCommandCopied: "Command copied.",
  connectCommandCopyFailed:
    "Clipboard access is unavailable. Select the command to copy it.",
  connectCommentExpectation:
    "A PR comment appears for confirmed drift when a previously passing check fails. It shows cited evidence; the Action does not write a suggested change to your PR. The current iMessage FIX flow can draft a correction for a supported server-port change.",
  connectFailed:
    "The repository could not be connected. Check administrator access and try again.",
  connectVisibilityChanged:
    "This repository was previously private. Its stored private results must be cleared before connecting it as public.",
  connectSignIn: "Sign in with GitHub to connect a repository.",
  imessageTitle: "Link iMessage",
  imessageIntro:
    "Receive drift alerts and request corrections by replying to iMessage.",
  imessagePhoneLabel: "Your iMessage phone number",
  imessagePhonePlaceholder: "+15551234567",
  imessagePhoneHint: "Include the country code, with no spaces or punctuation.",
  imessageInvalidPhone: "Enter a phone number like +15551234567.",
  imessageAction: "Send linking message",
  imessagePending: "Sending linking message",
  imessageSent:
    "Check Messages on your phone and reply with the LINK code shown in the message. The code works once and expires in 24 hours.",
  imessageRateLimit:
    "Three linking messages have been requested this hour. Try again later.",
  imessageUnavailable: "iMessage linking is not configured on this server.",
  imessageFailed: "The linking message could not be sent.",
  signInTitle: "Sign in with GitHub",
  signInIntro:
    "Sign in to connect repositories, add sources, and review checks you can access.",
  signInAction: "Continue with GitHub",
  signInConnected: "Signed in as",
  signInUnavailable:
    "Account status is unavailable. Try again after the server responds.",
  accountReposTitle: "Your GitHub repositories",
  accountReposIntro:
    "Your accessible repositories appear here after sign-in. Listing them does not start a scan or run their code.",
  accountReposLoading: "Loading your GitHub repositories",
  accountReposFailed:
    "Your repositories could not be loaded from GitHub. Try refreshing this page.",
  accountReposEmpty: "No accessible repositories were returned by GitHub.",
  accountReposSearch: "Find one of your repositories",
  accountReposSearchPlaceholder: "Search by name or description",
  accountReposFilter: "Show repositories",
  accountReposFilterAll: "All repositories",
  accountReposFilterUnscanned: "Unscanned repositories",
  accountReposPagePrevious: "Previous page",
  accountReposPageNext: "Next page",
  accountReposPageOf: "of",
  accountReposNoMatches: "No repositories match that search.",
  accountReposTruncated:
    "Showing the first 500 recently updated repositories. Bulk scan applies to these repositories.",
  accountReposPublic: "Public",
  accountReposPrivate: "Private",
  accountReposArchived: "Archived",
  accountReposFork: "Fork",
  accountReposConnected: "Connected",
  accountReposRuntimeEnabled: "Deep checks enabled",
  accountReposChecked: "Checked",
  accountReposScanned: "Scanned",
  accountReposOpenResult: "Open result",
  accountReposNotAdmin: "Admin access is needed to connect this repository.",
  accountReposConnect: "Connect",
  accountReposEnableRuntime: "Enable deep checks",
  accountReposConnecting: "Connecting",
  accountReposScan: "Check README",
  accountReposScanning: "Requesting scan",
  accountReposScanAll: "Scan all personal projects",
  accountReposScanAllHint:
    "Static checks, plus AI when configured. Only your public projects are included. Deep checks run in an owner-approved local checkout or after you add the GitHub Action; this button never runs repository code.",
  accountReposScanAllProgress: "Public scans requested",
  accountReposScanAllDone: "Public scan requests finished",
  accountReposScanAllFailed: "Some public scans could not start",
  accountReposScanQueued: "Scan queued",
  accountReposScanCached: "Saved scan ready",
  accountReposScanFailed: "This README scan could not start.",
  accountReposConnectFailed: "This repository could not be connected.",
  accountReposPrivateHint:
    "Private repositories need an explicit connection and GitHub Action for runtime checks.",
  accountReposPublicHint:
    "Ordinary public scans inspect documentation and metadata only. Your own public repositories can opt into deep checks in their GitHub Action.",
  accountReposManual: "Connect another repository",
  formRepoHint: "Use owner/repo from GitHub.",
  formUrlHint: "Paste an https page address.",
  formUrlPlaceholder: "https://docs.example.com/page",
  formInvalidRepo:
    "Choose a repository, or enter owner/repo or any GitHub link to it.",
  formInvalidUrl: "Enter a valid https URL.",
  commonRetry: "Try again",
  commonBack: "Back",
  commonUnknown: "Unknown",
  commonNone: "None recorded",
  commonOpen: "Open",
  commonSuccess: "Success",
  commonFailure: "Failure",
  commonPending: "Pending",
  commonLoading: "Loading",
  sourceNoRepos:
    "No repositories are connected yet. Connect one before adding a source.",
} as const;
